/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import controller.ControllerProdutos;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasCliente;
import controller.ControllerVendasProdutos;
import java.awt.Point;
import java.sql.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;
import model.ModelProdutosVendasProdutos;
import model.ModelVendas;
import model.ModelVendasCliente;
import util.BLDatas;

/**
 * DESENVOLVIDO EM JAVA 8_91 PATCH - C:\ProgramData\Oracle\Java\javapath;
 * JAVAHOME - C:\Program Files\Java\jdk1.8.0_91
 *
 * @author Darlan
 */
public class ViewVisualizarVendas extends javax.swing.JFrame {

    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProduto modelProdutos = new ModelProduto(); //Cria um objeto do tipo produto
    ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();
    ArrayList<ModelVendasCliente> listaModelVendasClientes = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasprodutos = new ArrayList<>();
    private ViewVendasFinal viewTelaVendas = new ViewVendasFinal();
    int linhaSelecionada;
    private ModelVendas modelVendaAlteracao;
    private static final Point point = new Point();
    BLDatas formatarData = new BLDatas();

    /**
     * Creates new form ViewVendas
     */
    public ViewVisualizarVendas() {
        initComponents();
        setLocationRelativeTo(null);
        carregarVendas();
        viewTelaVendas.dispose();
        setAlwaysOnTop(true);

    }

    public DefaultTableModel retornarModeloDaTabela() {
        return (DefaultTableModel) jtVendas.getModel();
    }

    public void marcarUltimaVenda() {

        jtVendas.setRowSelectionInterval(jtVendas.getRowCount() - 1, jtVendas.getRowCount() - 1);

    }

    public int pegarLinhaSelecionada(JTable pJtableVendas) {
        linhaSelecionada = 0;
        linhaSelecionada = pJtableVendas.getSelectedRow();
        return linhaSelecionada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfTotalBruto = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfvisualizarDesconto = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfTotalLiquido = new javax.swing.JFormattedTextField();
        jtfValorRecebido = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtVisualizarVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();
        jbNovo1 = new javax.swing.JButton();
        JbVisualizarVenda = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimirVenda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        barraDeMover1 = new javax.swing.JPanel();
        btMinimizar = new componentes.UJPanelImagem();
        btFechar = new componentes.UJPanelImagem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas Realizadas");
        setUndecorated(true);
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(119, 187, 153));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(136, 187, 221)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Sub-Total");

        jtfTotalBruto.setEditable(false);
        jtfTotalBruto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Desconto");

        jtfvisualizarDesconto.setEditable(false);
        jtfvisualizarDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Valor Total");

        jtfTotalLiquido.setEditable(false);
        jtfTotalLiquido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtfValorRecebido.setEditable(false);
        jtfValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Recebido");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTotalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfvisualizarDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTotalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfTotalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfvisualizarDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jtfTotalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido Selecionado para visualizar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jtVisualizarVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Prod.", "Nome Produto", "Quant.", "Valor Un.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVisualizarVenda.setMinimumSize(new java.awt.Dimension(0, 0));
        jtVisualizarVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtVisualizarVenda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 187, 221), 1, true));

        jLabel8.setText("Buscar pedido pelo código ou nome do cliente");

        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyReleased(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/iconfinder_search_285651.png"))); // NOI18N
        jbPesquisar.setText("Buscar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendas.setMinimumSize(new java.awt.Dimension(0, 0));
        jtVendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtVendas);
        if (jtVendas.getColumnModel().getColumnCount() > 0) {
            jtVendas.getColumnModel().getColumn(0).setMinWidth(110);
            jtVendas.getColumnModel().getColumn(0).setMaxWidth(110);
            jtVendas.getColumnModel().getColumn(2).setMinWidth(110);
            jtVendas.getColumnModel().getColumn(2).setMaxWidth(110);
        }

        jbNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/iconfinder_sign-add_299068.png"))); // NOI18N
        jbNovo1.setText("Novo");
        jbNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovo1ActionPerformed(evt);
            }
        });

        JbVisualizarVenda.setText("Visualizar Pedido");
        JbVisualizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbVisualizarVendaActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/iconfinder_trashcan_299071.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/iconfinder_pencil_285638.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimirVenda.setText("Imprimir Pedido");
        jbImprimirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirVendaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar por data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(JbVisualizarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbImprimirVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNovo1)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jbNovo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbExcluir)
                        .addComponent(jbAlterar))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JbVisualizarVenda)
                        .addComponent(jbImprimirVenda)))
                .addGap(13, 13, 13))
        );

        barraDeMover1.setBackground(new java.awt.Color(119, 187, 153));
        barraDeMover1.setPreferredSize(new java.awt.Dimension(515, 23));
        barraDeMover1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraDeMover1MouseDragged(evt);
            }
        });
        barraDeMover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraDeMover1MousePressed(evt);
            }
        });

        btMinimizar.setImagem(new java.io.File("C:\\SSDprojeto\\src\\imagens\\Fundos\\btMinimizar.png"));
        btMinimizar.setMinimumSize(new java.awt.Dimension(24, 24));
        btMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btMinimizarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btMinimizarLayout = new javax.swing.GroupLayout(btMinimizar);
        btMinimizar.setLayout(btMinimizarLayout);
        btMinimizarLayout.setHorizontalGroup(
            btMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        btMinimizarLayout.setVerticalGroup(
            btMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        btFechar.setImagem(new java.io.File("C:\\SSDprojeto\\src\\imagens\\Fundos\\btFecharJanela.png"));
        btFechar.setMinimumSize(new java.awt.Dimension(24, 24));
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btFecharMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btFecharLayout = new javax.swing.GroupLayout(btFechar);
        btFechar.setLayout(btFecharLayout);
        btFecharLayout.setHorizontalGroup(
            btFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        btFecharLayout.setVerticalGroup(
            btFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraDeMover1Layout = new javax.swing.GroupLayout(barraDeMover1);
        barraDeMover1.setLayout(barraDeMover1Layout);
        barraDeMover1Layout.setHorizontalGroup(
            barraDeMover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraDeMover1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraDeMover1Layout.setVerticalGroup(
            barraDeMover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeMover1Layout.createSequentialGroup()
                .addGroup(barraDeMover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraDeMover1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(barraDeMover1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbImprimirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirVendaActionPerformed
        // TODO add your handling code here:
        int linha = jtVendas.getSelectedRow();
        final int codigoVenda = (int) jtVendas.getValueAt(linha, 0);
        final Alertas aguarde = new Alertas("Aguarde, gerando pdf do pedido");
        aguarde.setVisible(true);
        Thread t = new Thread() {

            @Override
            public void run() {
                //Aqui fica o metodo imprimir do jaspersoft

                try {
                    controllerVendas.gerarRelatoriovenda(codigoVenda);
                    aguarde.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao imprimir pedido", "Erro: 14011231", JOptionPane.ERROR_MESSAGE);

                }

            }

        };
        t.start();


    }//GEN-LAST:event_jbImprimirVendaActionPerformed


    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        try {
            modelVendas = controllerVendas.getVendasController((int) jtVendas.getValueAt(pegarLinhaSelecionada(jtVendas), 0));
            setModelVendaAlteracao(modelVendas);
            if (viewTelaVendas.isVisible()) {
                viewTelaVendas.dispose();
                viewTelaVendas = new ViewVendasFinal(modelVendaAlteracao);
                viewTelaVendas.setViewVisualizarVendas(this);
                viewTelaVendas.setLocationRelativeTo(this);
                dispose();
                viewTelaVendas.setVisible(true);
            } else {
                viewTelaVendas = new ViewVendasFinal(modelVendaAlteracao);
                viewTelaVendas.setViewVisualizarVendas(this);
                viewTelaVendas.setLocationRelativeTo(this);
                dispose();
                viewTelaVendas.setVisible(true);
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecione a venda que deseja alterar", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // Comando para excluir venda no menu (consultar / excluir / alterar)
        /**
         * Declaro o int linha para marcar a linha selecionada que quero excluir
         * Declaro o int códigoVenda que seleciona o código na linha declarada,
         * no caso a coluna fica 0 pois vou pegar apenas o código da venda na
         * linha selecionada
         */
        int linha = jtVendas.getSelectedRow();//marca a linha selecionada

        int codigoVenda = (int) jtVendas.getValueAt(linha, 0);//pega o código da venda da linha selecionada e salva na variavel codigoVenda
        listaModelProdutos = new ArrayList<>();//Cria uma nova ListaModelProdutos para evitar receber lixo de outras vendas
        listaModelProdutosVendasprodutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);// Após o sinal de = o comando cria um array com todos os produtos da venda seleceionada entre parenteses
        for (ModelProdutosVendasProdutos listaModelProdutosVendasproduto : listaModelProdutosVendasprodutos) {
            modelProdutos = new ModelProduto();
            modelProdutos.setIdProduto(listaModelProdutosVendasproduto.getModelProdutos().getIdProduto());
            modelProdutos.setProEstoque(listaModelProdutosVendasproduto.getModelProdutos().getProEstoque() + listaModelProdutosVendasproduto.getModelProdutosDaVenda().getVenProQuantidadeVendida());
            listaModelProdutos.add(modelProdutos);
        }

        if (controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos)) {
            controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
            // Chamando o comando excluir, se o produto for excluído ele executa a mensagem de confirmação.
            if (controllerVendas.excluirVendasController(codigoVenda)) {
                System.out.println("Venda Excluída com sucesso");
                JOptionPane.showMessageDialog(this, "Venda Excluída com sucesso", "Tudo certo", JOptionPane.INFORMATION_MESSAGE);
                carregarVendas(jtfPesquisa.getText());
                DefaultTableModel model = (DefaultTableModel) jtVisualizarVenda.getModel();
                model.setNumRows(0);
                try {//Este try seleciona sempre a primeira linha da tabela após excluir uma venda, se não existir mais vendas ele muda para tela de cadastro de vendas
                    jtVendas.setRowSelectionInterval(0, 0);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Você não possui mais vendas, realize novas vendas para exibir algo aqui", "Atenção", JOptionPane.WARNING_MESSAGE);

                }

            } else {
                //se cair neste erro significa que tem algo errado no codigoVenda que foi passado(Pode ser que ele não exista no banco e etc)
                JOptionPane.showMessageDialog(this, "Erro ao Excluir a venda, consulte o código de erro AE-EV1", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //se cair neste erro é porquê tem algo errado na listaModelProdutos
            JOptionPane.showMessageDialog(this, "Erro ao Excluir a venda, consulte o código de erro AE-EV2", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    public void visualizarVenda(int pCodigoDaVenda) {

        try {

            int codigoVenda = pCodigoDaVenda; //pega o código da venda na linha selecionada
            ModelVendas modelVenda = controllerVendas.getVendasController(codigoVenda);
            listaModelProdutosVendasprodutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);//recupera a venda no banco
            DefaultTableModel modelo = (DefaultTableModel) jtVisualizarVenda.getModel();//Usa a tabela como modelo
            modelo.setNumRows(0);//zera a tabela
            int qtdProdTabela = listaModelProdutosVendasprodutos.size();//vê a quantidade de produtos na tabela

            double desconto = modelVenda.getVenDesconto();//retorna o valor do desconto salvo no banco de dados
            double valorRecebido = modelVenda.getVenValorRecebido();//retorna o valor recebido salvo no banco de dados
            jtfvisualizarDesconto.setText(String.valueOf(desconto));//aplica o desconto no jtf
            jtfValorRecebido.setText(String.valueOf(valorRecebido));//aplica o valor recebido no jtf

            for (int i = 0; i < qtdProdTabela; i++) {

                //Seta no campo número da venda o id da venda já cadastrada
                //jtfNumeroVenda.setText(String.valueOf(listaModelProdutosVendasprodutos.get(i).getModelVendasProdutos().getVendas()));
                //Preenche a tabela com os produtos da venda.
                modelo.addRow(new Object[]{
                    listaModelProdutosVendasprodutos.get(i).getModelProdutos().getIdProduto(),//ID atual do produto no banco
                    listaModelProdutosVendasprodutos.get(i).getModelProdutos().getProNome(),//Nome Atual do produto no banco
                    listaModelProdutosVendasprodutos.get(i).getModelProdutosDaVenda().getVenProQuantidadeVendida(),//quantidade vendida na data da compra
                    listaModelProdutosVendasprodutos.get(i).getModelProdutosDaVenda().getVenProValor(),//valor vendido na data da compra
                    listaModelProdutosVendasprodutos.get(i).getModelProdutosDaVenda().getVenProQuantidadeVendida() * listaModelProdutosVendasprodutos.get(i).getModelProdutosDaVenda().getVenProValor()//quantidade * valor = total
                });
            }

            jtfTotalLiquido.setText(modelVenda.getVenValorLiquido() + "");
            jtfTotalBruto.setText(modelVenda.getVenValorBruto() + "");
            jtfvisualizarDesconto.setText(modelVenda.getVenDesconto() + "");
            carregarVendas(jtfPesquisa.getText());

            //Seleciona na tabela de cima a venda que acabou de ser visualizada
            for (int i = 0; i < jtVendas.getRowCount(); i++) {
                if (jtVendas.getValueAt(i, 0).equals(codigoVenda)) {
                    jtVendas.setRowSelectionInterval(i, i);
                    break;
                }

            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível visualizar a venda selecionada.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            carregarVendas(jtfPesquisa.getText());
            marcarUltimaVenda();
        }
    }


    private void JbVisualizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbVisualizarVendaActionPerformed
        try {
            visualizarVenda((int) jtVendas.getValueAt(jtVendas.getSelectedRow(), 0));

        } catch (IndexOutOfBoundsException e) {
            marcarUltimaVenda();
            visualizarVenda((int) jtVendas.getValueAt(jtVendas.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_JbVisualizarVendaActionPerformed

    private void jbNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovo1ActionPerformed
        // TODO add your handling code here:
        try {
            viewTelaVendas.setViewVisualizarVendas(this);
            viewTelaVendas.setVisible(true);
            dispose();
            viewTelaVendas.iniciarNovaVenda();
        } catch (Exception e) {
            System.out.println("Exception ao tentar abrir tela de vendas");
            e.printStackTrace();
        }

    }//GEN-LAST:event_jbNovo1ActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        String pesquisa = jtfPesquisa.getText();
        carregarVendas(pesquisa);
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void btMinimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMinimizarMouseReleased
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btMinimizarMouseReleased

    private void btFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseReleased
        // TODO add your handling code here:

        dispose();
        //System.exit(0);
    }//GEN-LAST:event_btFecharMouseReleased

    private void barraDeMover1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDeMover1MouseDragged

        Point p = getLocation();
        setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_barraDeMover1MouseDragged

    private void barraDeMover1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDeMover1MousePressed

        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_barraDeMover1MousePressed

    private void jtfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String pesquisa = jtfPesquisa.getText();
            carregarVendas(pesquisa);

        }


    }//GEN-LAST:event_jtfPesquisaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            ViewCalendario viewCalendario = new ViewCalendario(this, true);
            viewCalendario.setVisible(true);

            carregarVendasPorData(formatarData.converterDataStringParaDate(viewCalendario.getDataSelecionada()));

        } catch (NullPointerException npe) {
            npe.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVisualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewVisualizarVendas().setVisible(true);
            }
        });
    }

    /**
     * Recarrega a tabela das vendas realizadas, na guia 2
     */
    public void carregarVendas() {

        DefaultTableModel modelo = (DefaultTableModel) jtVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.getListaVendasClienteController();

        int cont = listaModelVendasClientes.size();
        //Limpa tabela antes de carregar
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelCliente().getCliNome(),
                listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda()
            });
        }
    }

    /**
     * Recarrega a tabela das vendas realizadas buscando pelo id da venda ou
     * nome do cliente
     *
     * @param pBusca
     */
    void carregarVendas(String pBusca) {

        DefaultTableModel modelo = (DefaultTableModel) jtVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.getBuscarTodasVendasDoCLiente(pBusca);

        int cont = listaModelVendasClientes.size();
        //Limpa tabela antes de carregar
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelCliente().getCliNome(),
                formatarData.formatarData(listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda())
            });
        }
    }

    private void carregarVendasPorData(Date pDate) {

        DefaultTableModel modelo = (DefaultTableModel) jtVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.getBuscarVendasPorDataController(pDate);

        int cont = listaModelVendasClientes.size();

        //Limpa tabela antes de carregar
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {

            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelCliente().getCliNome(),
                formatarData.formatarData(listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda())
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbVisualizarVenda;
    private javax.swing.JPanel barraDeMover1;
    private componentes.UJPanelImagem btFechar;
    private componentes.UJPanelImagem btMinimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimirVenda;
    private javax.swing.JButton jbNovo1;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JTable jtVendas;
    private javax.swing.JTable jtVisualizarVenda;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JFormattedTextField jtfTotalBruto;
    private javax.swing.JFormattedTextField jtfTotalLiquido;
    private javax.swing.JFormattedTextField jtfValorRecebido;
    private javax.swing.JFormattedTextField jtfvisualizarDesconto;
    // End of variables declaration//GEN-END:variables

    public ModelVendas getModelVendaAlteracao() {
        return modelVendaAlteracao;
    }

    public void setModelVendaAlteracao(ModelVendas modelVendaAlteracao) {
        this.modelVendaAlteracao = modelVendaAlteracao;
    }

    public ViewVendasFinal getViewTelaVendas() {
        return viewTelaVendas;
    }

    public void setViewTelaVendas(ViewVendasFinal viewTelaVendas) {
        this.viewTelaVendas = viewTelaVendas;
    }

}
